version: '3.2'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: pd_frontend
    working_dir: /var/www/html
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
