version: '3.2'

services:
  frontend:
    image: nginx:1.17-alpine
    container_name: pd_frontend
    working_dir: /var/www/html
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/var/www/html
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf

  nginx:
    image: nginx:1.17-alpine
    container_name: pd_backend_nginx
    working_dir: /var/www/pizza-delivery
    ports:
      - "8050:80"
    volumes:
      - ./backend:/var/www/pizza-delivery
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: pd_backend
    working_dir: /var/www/pizza-delivery
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    env_file: ./backend/.env
    volumes:
      - ./backend:/var/www/pizza-delivery
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    command: /bin/sh -c "php artisan migrate && php artisan view:clear && /usr/local/sbin/php-fpm"
